services:
  - type: web
    name: vite-react-backend
    env: node
    plan: free
    rootDir: vite-react/packages/server
    buildCommand: npm install && npm run build
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # Render 会自动提供这些变量，或者你需要在面板上手动配置
      - key: DATABASE_URL
        sync: false # 表示需要在 Render 面板手动配置数据库连接字符串
      - key: APP_MODE
        value: production
    # 磁盘配置：解决免费版重启/休眠导致图片丢失的问题
    disk:
      name: uploads-disk
      mountPath: /opt/render/project/src/vite-react/packages/server/public/uploads
      sizeGB: 1
